"""add_performance_indexes

Revision ID: 147474db80a7
Revises: 22c1c4d603ad
Create Date: 2026-04-25 09:29:58.962570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147474db80a7'
down_revision: Union[str, None] = '22c1c4d603ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_achievements_employee_id'), 'achievements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_enrollments_employee_id'), 'enrollments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_enrollments_training_id'), 'enrollments', ['training_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_points_employee_id'), 'leaderboard_points', ['employee_id'], unique=False)
    op.create_index(op.f('ix_nominations_employee_id'), 'nominations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_nominations_nominated_by'), 'nominations', ['nominated_by'], unique=False)
    op.create_index(op.f('ix_nominations_status'), 'nominations', ['status'], unique=False)
    op.create_index(op.f('ix_nominations_training_id'), 'nominations', ['training_id'], unique=False)
    op.create_index(op.f('ix_training_effectiveness_enrollment_id'), 'training_effectiveness', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_training_effectiveness_evaluated_by'), 'training_effectiveness', ['evaluated_by'], unique=False)
    op.create_index(op.f('ix_training_effectiveness_status'), 'training_effectiveness', ['status'], unique=False)
    op.create_index(op.f('ix_training_effectiveness_training_id'), 'training_effectiveness', ['training_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_effectiveness_training_id'), table_name='training_effectiveness')
    op.drop_index(op.f('ix_training_effectiveness_status'), table_name='training_effectiveness')
    op.drop_index(op.f('ix_training_effectiveness_evaluated_by'), table_name='training_effectiveness')
    op.drop_index(op.f('ix_training_effectiveness_enrollment_id'), table_name='training_effectiveness')
    op.drop_index(op.f('ix_nominations_training_id'), table_name='nominations')
    op.drop_index(op.f('ix_nominations_status'), table_name='nominations')
    op.drop_index(op.f('ix_nominations_nominated_by'), table_name='nominations')
    op.drop_index(op.f('ix_nominations_employee_id'), table_name='nominations')
    op.drop_index(op.f('ix_leaderboard_points_employee_id'), table_name='leaderboard_points')
    op.drop_index(op.f('ix_enrollments_training_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_employee_id'), table_name='enrollments')
    op.drop_index(op.f('ix_achievements_employee_id'), table_name='achievements')
    # ### end Alembic commands ###
