"""Add secure_token to AttendanceSession

Revision ID: 21a7412213bc
Revises: 147474db80a7
Create Date: 2026-05-21 09:33:07.006791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21a7412213bc'
down_revision: Union[str, None] = '147474db80a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_attendance_id', table_name='training_attendance')
    op.drop_table('training_attendance')
    op.add_column('attendance_sessions', sa.Column('secure_token', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_attendance_sessions_secure_token'), 'attendance_sessions', ['secure_token'], unique=True)
    op.alter_column('enrollments', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint('nominations_manager_id_fkey', 'nominations', type_='foreignkey')
    op.create_foreign_key(None, 'nominations', 'employees', ['manager_id'], ['id'])
    op.alter_column('trainings', 'is_attendance_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'is_attendance_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'nominations', type_='foreignkey')
    op.create_foreign_key('nominations_manager_id_fkey', 'nominations', 'employees', ['manager_id'], ['id'], ondelete='SET NULL')
    op.alter_column('enrollments', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_attendance_sessions_secure_token'), table_name='attendance_sessions')
    op.drop_column('attendance_sessions', 'secure_token')
    op.create_table('training_attendance',
    sa.Column('enrollment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', 'EXCUSED', 'LATE', name='attendancestatus'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name='training_attendance_enrollment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='training_attendance_pkey')
    )
    op.create_index('ix_training_attendance_id', 'training_attendance', ['id'], unique=False)
    # ### end Alembic commands ###
