"""Add onboarding fields and system settings

Revision ID: 68e75e031b56
Revises: 33e1866f3bd7
Create Date: 2026-06-18 10:12:49.572433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e75e031b56'
down_revision: Union[str, None] = '33e1866f3bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('never_show_welcome_back', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'never_show_welcome_back')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
