"""add_submission_deadline_to_effectiveness

Revision ID: 749adf78c6f1
Revises: 21a7412213bc
Create Date: 2026-05-25 15:16:47.358855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749adf78c6f1'
down_revision: Union[str, None] = '21a7412213bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_effectiveness', sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_effectiveness', 'submission_deadline')
    # ### end Alembic commands ###
