"""Change preferred_date to string

Revision ID: c211caf9b272
Revises: bd466703002e
Create Date: 2026-04-24 09:46:08.448253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c211caf9b272'
down_revision: Union[str, None] = 'bd466703002e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('streak_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('self_nominations', 'preferred_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('training_effectiveness', sa.Column('learnings_summary', sa.Text(), nullable=True))
    op.add_column('training_effectiveness', sa.Column('work_application', sa.Text(), nullable=True))
    op.add_column('training_effectiveness', sa.Column('suggestions', sa.Text(), nullable=True))
    op.add_column('training_effectiveness', sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'REVIEWED', name='effectivenessstatus'), nullable=False, server_default='PENDING'))
    op.add_column('training_effectiveness', sa.Column('manager_comments', sa.Text(), nullable=True))
    op.add_column('training_effectiveness', sa.Column('manager_score', sa.Float(), nullable=True))
    op.add_column('training_effectiveness', sa.Column('digital_signature_url', sa.Text(), nullable=True))
    op.add_column('training_effectiveness', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('training_effectiveness', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'training_effectiveness', 'users', ['reviewed_by'], ['id'])
    op.add_column('trainings', sa.Column('cost', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('trainings', sa.Column('skills_covered', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'skills_covered')
    op.drop_column('trainings', 'cost')
    op.drop_constraint(None, 'training_effectiveness', type_='foreignkey')
    op.drop_column('training_effectiveness', 'reviewed_by')
    op.drop_column('training_effectiveness', 'reviewed_at')
    op.drop_column('training_effectiveness', 'digital_signature_url')
    op.drop_column('training_effectiveness', 'manager_score')
    op.drop_column('training_effectiveness', 'manager_comments')
    op.drop_column('training_effectiveness', 'status')
    op.drop_column('training_effectiveness', 'suggestions')
    op.drop_column('training_effectiveness', 'work_application')
    op.drop_column('training_effectiveness', 'learnings_summary')
    op.alter_column('self_nominations', 'preferred_date',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('employees', 'streak_count')
    # ### end Alembic commands ###
