"""fix created_by in training_import_history

Revision ID: dd5558b9f0f8
Revises: ffb58b53b1a2
Create Date: 2026-06-13 15:49:58.517790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5558b9f0f8'
down_revision: Union[str, None] = 'ffb58b53b1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'training_import_history', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_import_history', type_='foreignkey')
    # ### end Alembic commands ###
